### ISSUE TITLE
SMF_URLs_Paths.php doesn't recognize "&"

### ISSUE THREAD

**Issue by MechDR** [sbulen/sjrbTools#6]
I've been using this script to replace parts of URLs and some text on my forum. Everything's pretty much OK with the script, except that it doesn't return any results if the string start with **&**, as in if the string I'm trying to replace is **&feature=related**. I know this is not how the script is meant to be used, but it would be nice if it doesn't "choke" on certain characters.

Thanks for making this wonderful tool 👍 .

**Comment by sbulen** [comment]
Many columns in the db are html-encoded.  So I suspect the string you should be looking for is:
`&amp;feature=related`

You should confirm this by looking in the DB.

Note your substitution should be html-encoded as well...  If you wanted to change **&feature=related** to **&feature=orphan**
then the substitution should be:
`&amp;feature=orphan`

**Comment by MechDR** [comment]
Yep, that worked ;).

Anyhow, I was thinking more in the lines of making it a general "search and replace script", adding escape sequences for special reserved characters, like **&** (amp), so that it doesn't glitch on them ;). Maybe making it UTF-8 compatible as well ;).

**Comment by sbulen** [comment]
It is currently fully utf8 compatible.  Note that SMF sometimes htmlencodes utf-8 characters, so you would need to look at the values in the DB to understand what the proper substitutions to request are.  (Just like above.)

The tool does exactly what it says it does - help you build safe test environments by making url & path substitutions.  Yes, it can be helpful with some global issues (e.g., when postimage.org changed its url...).  I have considered a more friendly version more appropriate for generic text substitutions in posts, but I admit I'm concerned with making it too easy to modify user posts...

![image](https://user-images.githubusercontent.com/23568484/103941011-1c728e80-50e3-11eb-800a-6f6287f9c0a7.png)

**Comment by MechDR** [comment]
The table's collation (messages) is set to utf8_general_ci. Here's how the messages table looks in phpMyAdmin.

![SHOT2085](https://user-images.githubusercontent.com/45944962/103951650-625d4000-513f-11eb-9474-63d29e5203d0.png)

And here's what SMF_URLs_Paths.php outputs when it's being run with a word (години) that evidently appears in at least one message.

![SHOT0127](https://user-images.githubusercontent.com/45944962/103952548-e4019d80-5140-11eb-9769-bca3c3b2b958.png)

So I thought "Hm, what if I save the file as UTF-8 instead of ANSI" and that did the trick ;)... except for the error at the top, which is not DB related, and the unknown symbols at the beginning and end of the message preview (marked with red), but other than that, yeah, it works 👍. Just have to remember to save the file as UTF-8 ;).

![SHOT0128](https://user-images.githubusercontent.com/45944962/103953389-532bc180-5142-11eb-984b-bad5d22e504d.png)

Regarding your concern with making it too easy to edit user's posts... every tool can be misused, so, if it was me, I wouldn't give it much thought... my 2 cents ;). Heck, it's really easy to misuse this one, LOL :D.

**Comment by sbulen** [comment]
I believe the primary problem is with your editor.  As shown above, it works fine for utf8.  When you say "save the file as" utf8, that is a function of your editor.  You need to tell your editor whether you are working with utf8 or ANSI.  The file itself doesn't have a UTF8 vs ANSI attribute...  It's just text...

The part where you are correct...  The black squares at the beginning & end are indeed caused by truncation mid utf8 character.  That, I will likely fix.

**Comment by MechDR** [comment]
> 
> 
> I believe the primary problem is with your editor. As shown above, it works fine for utf8. When you say "save the file as" utf8, that is a function of your editor. You need to tell your editor whether you are working with utf8 or ANSI. The file itself doesn't have a UTF8 vs ANSI attribute... It's just text...

Yeah, but I downloaded the tools from source as zip, they're all saved as ANSI by default... and since my OS has language support installed for my native language, even if the file is saved as ANSI and I've used Cyrillic characters in the file, almost every editor nowadays will display the characters correctly, even if the file is saved as ANSI, not UTF-8.

My point is, maybe it's wise to save them as UTF-8 instead of ANSI in the repo, that's all ;).

**Comment by sbulen** [comment]
Interesting.  They are all UTF8 in the repo - that is git's default.  All tools I have tell me all the files are UTF8.  Nothing is ANSI, anywhere.

Note that, since there are no multi-byte or extended characters in the source code, bear in mind that - bitwise - there is no difference whatsoever in a utf8 encoded file and an ansi encoded file.  utf8 is a superset.  If you only use the subset, as in this case, _they are the exact same, bit-for-bit..._  Further, there is no 'ansi' vs 'utf8' file attribute.  You have to tell your editor that info.  

I still believe the challenge here is that your editor is assuming ANSI because it is not finding any UTF8 characters in the source code.  This is common editor behavior.  I still think the solution is to have your editor default to utf8 instead of ANSI.  

What editor are you using?

**Comment by sbulen** [comment]
Substring display has been fixed.  You should not see the black diamonds at the beginning or end of the snippets.

**Comment by MechDR** [comment]
> 
> 
> I still believe the challenge here is that your editor is assuming ANSI because it is not finding any UTF8 characters in the source code. This is common editor behavior. I still think the solution is to have your editor default to utf8 instead of ANSI.
> 
> What editor are you using?

Ah, yes, you're right ;). I use Notepad on Win8.1 for quick editing (I've got a context menu entry "Open with Notepad" added on every file, I find it useful for quick checks and edits) but for some reason, it doesn't recognize that it's an UTF-8 file. It interprets the encoding as ANSI and when you edit something, it saves it as ANSI.

Sorry for the false report ;).

> 
> 
> Substring display has been fixed. You should not see the black diamonds at the beginning or end of the snippets.

Great :). The issue can be closed.

**Comment by sbulen** [comment]
Thanks for the feedback!

Always helpful to talk these things thru...  It made me read up more on git...
